/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Documents\\Programming\\NTMDevelopment\\weeby-js\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-52347a36",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52347a36").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6ba0dc42",
    path: "/docs/class/generators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ba0dc42").then(next)
    },
  },
  {
    name: "v-d1d19882",
    path: "/docs/class/custom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d1d19882").then(next)
    },
  },
  {
    name: "v-687a3f7f",
    path: "/docs/class/client.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-687a3f7f").then(next)
    },
  },
  {
    name: "v-16e1ff8e",
    path: "/docs/class/gif.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16e1ff8e").then(next)
    },
  },
  {
    name: "v-3382df86",
    path: "/docs/class/effects.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3382df86").then(next)
    },
  },
  {
    name: "v-0e456d70",
    path: "/docs/functions.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e456d70").then(next)
    },
  },
  {
    name: "v-43c0709f",
    path: "/docs/class/json.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43c0709f").then(next)
    },
  },
  {
    name: "v-9c00d702",
    path: "/docs/class/overlays.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9c00d702").then(next)
    },
  },
  {
    name: "v-6e984242",
    path: "/docs/guide/authentication.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e984242").then(next)
    },
  },
  {
    name: "v-4086214e",
    path: "/docs/intro.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4086214e").then(next)
    },
  },
  {
    name: "v-9fa73b42",
    path: "/docs/guide/contributing.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9fa73b42").then(next)
    },
  },
  {
    name: "v-01ecd2bf",
    path: "/docs/guide/examples.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01ecd2bf").then(next)
    },
  },
  {
    name: "v-98230292",
    path: "/docs/guide/license.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-98230292").then(next)
    },
  },
  {
    name: "v-0dd83882",
    path: "/docs/guide/setup.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0dd83882").then(next)
    },
  },
  {
    name: "v-4dccc79b",
    path: "/docs/guide/support.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4dccc79b").then(next)
    },
  },
  {
    name: "v-ba258642",
    path: "/docs/guide/quicklinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba258642").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]