/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Documents\\Programming\\NTMDevelopment\\weeby-js\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-944d44ac",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-944d44ac").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7bbc5849",
    path: "/docs/class/effects.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7bbc5849").then(next)
    },
  },
  {
    name: "v-153f8ecb",
    path: "/docs/class/custom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-153f8ecb").then(next)
    },
  },
  {
    name: "v-1d0831ab",
    path: "/docs/class/json.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d0831ab").then(next)
    },
  },
  {
    name: "v-41a8ecea",
    path: "/docs/class/overlays.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41a8ecea").then(next)
    },
  },
  {
    name: "v-073bfd08",
    path: "/docs/functions.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-073bfd08").then(next)
    },
  },
  {
    name: "v-3aa8d776",
    path: "/docs/class/gif.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3aa8d776").then(next)
    },
  },
  {
    name: "v-20bca1eb",
    path: "/docs/guide/authentication.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20bca1eb").then(next)
    },
  },
  {
    name: "v-31fbbe2a",
    path: "/docs/class/generators.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31fbbe2a").then(next)
    },
  },
  {
    name: "v-186ee92a",
    path: "/docs/guide/contributing.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-186ee92a").then(next)
    },
  },
  {
    name: "v-2f18c7cb",
    path: "/docs/guide/examples.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f18c7cb").then(next)
    },
  },
  {
    name: "v-496c46c3",
    path: "/docs/guide/license.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-496c46c3").then(next)
    },
  },
  {
    name: "v-8080682a",
    path: "/docs/guide/quicklinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8080682a").then(next)
    },
  },
  {
    name: "v-c120dc6a",
    path: "/docs/guide/setup.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c120dc6a").then(next)
    },
  },
  {
    name: "v-396ae0b2",
    path: "/docs/guide/support.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-396ae0b2").then(next)
    },
  },
  {
    name: "v-6e64fd4c",
    path: "/docs/intro.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e64fd4c").then(next)
    },
  },
  {
    name: "v-32bacaea",
    path: "/docs/class/client.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32bacaea").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]