/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Weeby-JS",
  "description": "",
  "base": "/weeby-js/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/weeby-js/images/favicon.ico",
        "alt": "Weeby-JS Icon"
      }
    ],
    [
      "meta",
      {
        "name": "og:title",
        "content": "Weeby-JS"
      }
    ],
    [
      "meta",
      {
        "name": "og:description",
        "content": "Official JavaScript Wrapper for Weeby API."
      }
    ],
    [
      "meta",
      {
        "name": "og:type",
        "content": "website"
      }
    ],
    [
      "meta",
      {
        "name": "og:url",
        "content": "https://js.weebyapi.xyz/"
      }
    ],
    [
      "meta",
      {
        "name": "og:locale",
        "content": "en_US"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/images/Icon.png",
        "heroText": "Weeby-JS",
        "tagline": "Official JavaScript Wrapper for Weeby API.",
        "actionText": "Get Started →",
        "actionLink": "/docs/intro",
        "footer": "Copyright © 2021 NTM Development • Version 1.1.0 • GNU GENERAL PUBLIC License"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-52347a36",
      "path": "/",
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "generators",
      "frontmatter": {
        "title": "generators"
      },
      "regularPath": "/docs/class/generators.html",
      "relativePath": "docs/class/generators.md",
      "key": "v-6ba0dc42",
      "path": "/docs/class/generators.html",
      "headers": [
        {
          "level": 2,
          "title": "Generators",
          "slug": "generators-2"
        },
        {
          "level": 3,
          "title": "generators.oneImage(options) ⇒",
          "slug": "generators-oneimage-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.twoImages(options) ⇒",
          "slug": "generators-twoimages-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.text(options) ⇒",
          "slug": "generators-text-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.twoText(options) ⇒",
          "slug": "generators-twotext-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.textImage(options) ⇒",
          "slug": "generators-textimage-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.friendship(options) ⇒",
          "slug": "generators-friendship-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.demotivational(options) ⇒",
          "slug": "generators-demotivational-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.rip(options) ⇒",
          "slug": "generators-rip-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.tweet(options) ⇒",
          "slug": "generators-tweet-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.tweetFetch(options) ⇒",
          "slug": "generators-tweetfetch-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.spotifySearch(options) ⇒",
          "slug": "generators-spotifysearch-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.spotifyNp(options) ⇒",
          "slug": "generators-spotifynp-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.currency(options) ⇒",
          "slug": "generators-currency-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "generators.color(hex) ⇒",
          "slug": "generators-color-hex-⇒-promise-buffer"
        }
      ],
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "custom",
      "frontmatter": {
        "title": "custom"
      },
      "regularPath": "/docs/class/custom.html",
      "relativePath": "docs/class/custom.md",
      "key": "v-d1d19882",
      "path": "/docs/class/custom.html",
      "headers": [
        {
          "level": 2,
          "title": "Custom",
          "slug": "custom-2"
        },
        {
          "level": 3,
          "title": "custom.greeting(options) ⇒",
          "slug": "custom-greeting-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "custom.booster(options) ⇒",
          "slug": "custom-booster-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "custom.rank(options) ⇒",
          "slug": "custom-rank-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "custom.levelUp(options) ⇒",
          "slug": "custom-levelup-options-⇒-promise-buffer"
        }
      ],
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "index",
      "frontmatter": {
        "title": "index"
      },
      "regularPath": "/docs/class/client.html",
      "relativePath": "docs/class/client.md",
      "key": "v-687a3f7f",
      "path": "/docs/class/client.html",
      "headers": [
        {
          "level": 2,
          "title": "Classes",
          "slug": "classes"
        },
        {
          "level": 2,
          "title": "Client",
          "slug": "client"
        },
        {
          "level": 2,
          "title": "WeebyAPI",
          "slug": "weebyapi"
        },
        {
          "level": 3,
          "title": "new WeebyAPI(token)",
          "slug": "new-weebyapi-token"
        }
      ],
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "gif",
      "frontmatter": {
        "title": "gif"
      },
      "regularPath": "/docs/class/gif.html",
      "relativePath": "docs/class/gif.md",
      "key": "v-16e1ff8e",
      "path": "/docs/class/gif.html",
      "headers": [
        {
          "level": 2,
          "title": "GIF",
          "slug": "gif-2"
        },
        {
          "level": 3,
          "title": "giF.fetch(type) ⇒",
          "slug": "gif-fetch-type-⇒-promise-string"
        }
      ],
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "effects",
      "frontmatter": {
        "title": "effects"
      },
      "regularPath": "/docs/class/effects.html",
      "relativePath": "docs/class/effects.md",
      "key": "v-3382df86",
      "path": "/docs/class/effects.html",
      "headers": [
        {
          "level": 2,
          "title": "Effects",
          "slug": "effects-2"
        },
        {
          "level": 3,
          "title": "effects.general(options) ⇒",
          "slug": "effects-general-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "effects.intensity(options) ⇒",
          "slug": "effects-intensity-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "effects.level(options) ⇒",
          "slug": "effects-level-options-⇒-promise-buffer"
        },
        {
          "level": 3,
          "title": "effects.resize(options) ⇒",
          "slug": "effects-resize-options-⇒-promise-buffer"
        }
      ],
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "All functions",
      "frontmatter": {},
      "regularPath": "/docs/functions.html",
      "relativePath": "docs/functions.md",
      "key": "v-0e456d70",
      "path": "/docs/functions.html",
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "json",
      "frontmatter": {
        "title": "json"
      },
      "regularPath": "/docs/class/json.html",
      "relativePath": "docs/class/json.md",
      "key": "v-43c0709f",
      "path": "/docs/class/json.html",
      "headers": [
        {
          "level": 2,
          "title": "Classes",
          "slug": "classes"
        },
        {
          "level": 2,
          "title": "Typedefs",
          "slug": "typedefs"
        },
        {
          "level": 2,
          "title": "JSON",
          "slug": "json-2"
        },
        {
          "level": 3,
          "title": "json.word(type) ⇒",
          "slug": "json-word-type-⇒-promise-string"
        },
        {
          "level": 3,
          "title": "json.response(type) ⇒",
          "slug": "json-response-type-⇒-promise-string"
        },
        {
          "level": 3,
          "title": "json.textFormat(options) ⇒",
          "slug": "json-textformat-options-⇒-promise-string"
        },
        {
          "level": 3,
          "title": "json.lyrics(query) ⇒ [](#lyricsResponse)",
          "slug": "json-lyrics-query-⇒-promise-lyricsresponse"
        },
        {
          "level": 3,
          "title": "json.stats() ⇒",
          "slug": "json-stats-⇒-promise-object"
        },
        {
          "level": 2,
          "title": "lyricsResponse :",
          "slug": "lyricsresponse-object"
        }
      ],
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "overlays",
      "frontmatter": {
        "title": "overlays"
      },
      "regularPath": "/docs/class/overlays.html",
      "relativePath": "docs/class/overlays.md",
      "key": "v-9c00d702",
      "path": "/docs/class/overlays.html",
      "headers": [
        {
          "level": 2,
          "title": "Overlays",
          "slug": "overlays-2"
        },
        {
          "level": 3,
          "title": "overlays.fetch(options) ⇒",
          "slug": "overlays-fetch-options-⇒-promise-buffer"
        }
      ],
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "Authentication",
      "frontmatter": {},
      "regularPath": "/docs/guide/authentication.html",
      "relativePath": "docs/guide/authentication.md",
      "key": "v-6e984242",
      "path": "/docs/guide/authentication.html",
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "Intro",
      "frontmatter": {},
      "regularPath": "/docs/intro.html",
      "relativePath": "docs/intro.md",
      "key": "v-4086214e",
      "path": "/docs/intro.html",
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "Contributing",
      "frontmatter": {},
      "regularPath": "/docs/guide/contributing.html",
      "relativePath": "docs/guide/contributing.md",
      "key": "v-9fa73b42",
      "path": "/docs/guide/contributing.html",
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "Examples",
      "frontmatter": {},
      "regularPath": "/docs/guide/examples.html",
      "relativePath": "docs/guide/examples.md",
      "key": "v-01ecd2bf",
      "path": "/docs/guide/examples.html",
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "License",
      "frontmatter": {},
      "regularPath": "/docs/guide/license.html",
      "relativePath": "docs/guide/license.md",
      "key": "v-98230292",
      "path": "/docs/guide/license.html",
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "Setup",
      "frontmatter": {},
      "regularPath": "/docs/guide/setup.html",
      "relativePath": "docs/guide/setup.md",
      "key": "v-0dd83882",
      "path": "/docs/guide/setup.html",
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "Support",
      "frontmatter": {},
      "regularPath": "/docs/guide/support.html",
      "relativePath": "docs/guide/support.md",
      "key": "v-4dccc79b",
      "path": "/docs/guide/support.html",
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    },
    {
      "title": "Quick Links",
      "frontmatter": {},
      "regularPath": "/docs/guide/quicklinks.html",
      "relativePath": "docs/guide/quicklinks.md",
      "key": "v-ba258642",
      "path": "/docs/guide/quicklinks.html",
      "lastUpdated": "8/23/2021, 12:52:58 PM"
    }
  ],
  "themeConfig": {
    "logo": "/images/Icon.png",
    "yuu": {
      "colorThemes": [
        "purple",
        "blue"
      ],
      "defaultColorTheme": "purple",
      "disableThemeIgnore": true,
      "labels": {
        "darkTheme": "Dark Mode",
        "logo": "WeebyLogo"
      }
    },
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Documentation",
        "link": "/index/intro"
      },
      {
        "text": "Main Website",
        "link": "https://weebyapi.xyz/"
      },
      {
        "text": "Support Server",
        "link": "https://weebyapi.xyz/discord"
      },
      {
        "text": "NPM",
        "link": "https://www.npmjs.com/package/weeby-js"
      }
    ],
    "sidebar": {
      "/docs/": [
        "intro",
        "functions",
        {
          "title": "Guide",
          "collapsable": true,
          "children": [
            "/docs/guide/setup",
            "/docs/guide/authentication",
            "/docs/guide/examples",
            "/docs/guide/contributing",
            "/docs/guide/support",
            "/docs/guide/quicklinks",
            "/docs/guide/license"
          ]
        },
        {
          "title": "Classes",
          "collapsable": true,
          "children": [
            "/docs/class/client",
            "/docs/class/custom",
            "/docs/class/effects",
            "/docs/class/generators",
            "/docs/class/gif",
            "/docs/class/json",
            "/docs/class/overlays"
          ]
        }
      ]
    },
    "searchMaxSuggestions": 5,
    "sidebarDepth": 2,
    "searchPlaceholder": "Search Docs...",
    "lastUpdated": "Last Updated",
    "repo": "ntm-development/weeby-js",
    "editLinks": true,
    "docsBranch": "master",
    "editLinkText": "Edit on GitHub",
    "noFoundPageByTencent": false
  }
}